package com.tnesoftware.rsquestfilter.tools;

import java.util.HashSet;
import java.util.Set;

import com.tnesoftware.rsquestfilter.Quest;
import com.tnesoftware.rsquestfilter.Quest.Difficulty;
import com.tnesoftware.rsquestfilter.Quest.Length;
import com.tnesoftware.rsquestfilter.Skill.Type;
import com.tnesoftware.rsquestfilter.impl.MiniQuest;
import com.tnesoftware.rsquestfilter.impl.QuestImpl;
import com.tnesoftware.rsquestfilter.impl.SkillRequirement;

public class QuestConstants {
	

	public static final Quest animalMagnetism;
	public static final Quest anotherSliceOfHam;
	public static final Quest betweenARock;
	public static final Quest bigChompyBirdHunting;
	public static final Quest biohazard;
	public static final Quest blackKnightsfortress;
	public static final Quest cabinFever;
	public static final Quest clockTower;
	public static final Quest coldWar;
	public static final Quest contact;
	public static final Quest cooksAssistant;
	public static final Quest creatureOfFenken;
	public static final Quest darknessOfHallowvale;
	public static final Quest deathPlateau;
	public static final Quest deathToTheDorgeshuun;
	public static final Quest demonSlayer;
	public static final Quest desertTreasure;
	public static final Quest deviousMinds;
	public static final Quest digsite;
	public static final Quest doricsQuest;
	public static final Quest dragonSlayer;
	public static final Quest dreamMentor;
	public static final Quest druidicRitual;
	public static final Quest dwarfCannon;
	public static final Quest eadgarsRuse;
	public static final Quest eaglesPeak;
	public static final Quest elementalWorkshopI;
	public static final Quest elementalWorkshopII;
	public static final Quest enakhrasLament;
	public static final Quest enlightenedJourney;
	public static final Quest ernestTheChicken;
	public static final Quest eyesOfGlouphrie;
	public static final Quest fairytaleI;
	public static final Quest fairytaleII;
	public static final Quest familyCrest;
	public static final Quest feud;
	public static final Quest fightArena;
	public static final Quest fishingContest;
	public static final Quest forgettableTale;
	public static final Quest fremennikIsles;
	public static final Quest fremennikTrials;
	public static final Quest gardenOfTranquility;
	public static final Quest gertrudesCat;
	public static final Quest ghostsAhoy;
	public static final Quest giantDwarf;
	public static final Quest goblinDiplomacy;
	public static final Quest golem;
	public static final Quest grandTree;
	public static final Quest greatBrainRobbery;
	public static final Quest grimTales;
	public static final Quest handInTheSand;
	public static final Quest hauntedMine;
	public static final Quest hazeelCult;
	public static final Quest heroesQuest;
	public static final Quest holyGrail;
	public static final Quest horrorFromTheDeep;
	public static final Quest icthlarinsHelper;
	public static final Quest impCatcher;
	public static final Quest inAidOfTheMyreque;
	public static final Quest inSearchOfTheMyreque;
	public static final Quest junglePotion;
	public static final Quest kingsRansom;
	public static final Quest knightsSword;
	public static final Quest legendsQuest;
	public static final Quest lostCity;
	public static final Quest lostTribe;
	public static final Quest lunarDiplomacy;
	public static final Quest makingHistory;
	public static final Quest merlinsCrystal;
	public static final Quest monksFriend;
	public static final Quest monkeyMadness;
	public static final Quest monkeyMadnessII;
	public static final Quest mountainDaughter;
	public static final Quest mourningsEndI;
	public static final Quest mourningsEndII;
	public static final Quest murderMystery;
	public static final Quest myArmsBigAdventure;
	public static final Quest natureSpirit;
	public static final Quest observatoryQuest;
	public static final Quest olafsQuest;
	public static final Quest oneSmallFavour;
	public static final Quest piratesTreasure;
	public static final Quest plagueCity;
	public static final Quest priestInPeril;
	public static final Quest princeAliRescue;
	public static final Quest ragAndBoneMan;
        public static final Quest ragAndBoneManMini;
	public static final Quest ratCatchers;
	
	/** All RFD Parts are separate */
	public static final Quest rfdCook; 
	public static final Quest rfdMountainDwarf;
	public static final Quest rfdGoblins;
	public static final Quest rfdPiratePete;
	public static final Quest rfdLumbridgeGuide;
	public static final Quest rfdEvilDave;
	public static final Quest rfdSkrachUglogwee;
	public static final Quest rfdSirAmikVarze;
	public static final Quest rfdKingAwowogei;
	public static final Quest rfdFinalFights;
	
	public static final Quest recruitmentDrive;
	public static final Quest regicide;
	public static final Quest romeoAndJuliet;
	public static final Quest rovingElves;
	public static final Quest royalTrouble;
	public static final Quest rumDeal;
	public static final Quest runeMysteries;
	public static final Quest scorpionCatcher;
	public static final Quest seaSlug;
	public static final Quest shadesOfMortton;
	public static final Quest shadowOfTheStorm;
	public static final Quest sheepHerder;
	public static final Quest sheepShearer;
	public static final Quest shieldOfArrav;
	public static final Quest shiloVillage;
	public static final Quest slugMenace;
	public static final Quest soulsBane;
	public static final Quest spiritsOfTheElid;
	public static final Quest swanSong;
	public static final Quest taiBwoWannaiTrio;
	public static final Quest tailOfTwoCats;
	public static final Quest tearsOfGuthix;
	public static final Quest templeOfIkov;
	public static final Quest restlessGhost;
	public static final Quest throneOfMiscellania;
	public static final Quest touristTrap;
	public static final Quest towerOfLife;
	public static final Quest treeGnomeVillage;
	public static final Quest tribalTotem;
	public static final Quest trollRomance;
	public static final Quest trollStronghold;
	public static final Quest undergroundPass;
	public static final Quest vampireSlayer;
	public static final Quest wanted;
	public static final Quest watchtower;
	public static final Quest waterfallQuest;
	public static final Quest whatLiesBelow;
	public static final Quest witchsHouse;
	public static final Quest witchsPotion;
	public static final Quest zogreFleshEaters;
	
	public static final MiniQuest mageOfZamorak;
	public static final MiniQuest alfredBarcrawl;
        public static final MiniQuest skippyAndTheMogres;
	
	public static Set<Quest> allQuestSet;
	
	static
	{
		/** Initialize each quest */
		animalMagnetism = 	new QuestImpl( "Animal Magnetism", 1, Length.Medium, Difficulty.Intermediate,"http://www.runehq.com/oldschoolquest/animal-magnetism" );
		anotherSliceOfHam = 	new QuestImpl( "Another Slice of H.A.M.", 1, Length.Medium, Difficulty.Intermediate, "http://www.runehq.com/oldschoolquest/another-slice-of-h-a-m" );
		betweenARock = 		new QuestImpl( "Between a Rock...", 2, Length.Medium, Difficulty.Experienced, "http://www.runehq.com/oldschoolquest/between-a-rock" );
		bigChompyBirdHunting = 	new QuestImpl( "Big Chompy Bird Hunting", 2, Length.Short, Difficulty.Intermediate, "http://www.runehq.com/oldschoolquest/big-chompy-bird-hunting" );
		biohazard = 		new QuestImpl( "Biohazard", 3, Length.Long, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/biohazard" );
		blackKnightsfortress = 	new QuestImpl( "Black Knights' Fortress", 3, Length.Short, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/black-knights-fortress" );
		cabinFever = 		new QuestImpl( "Cabin Fever", 2, Length.Medium, Difficulty.Experienced, "http://www.runehq.com/oldschoolquest/cabin-fever" );
		clockTower = 		new QuestImpl( "Clock Tower", 1, Length.Medium, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/clock-tower" );
		coldWar = 		new QuestImpl( "Cold War", 1, Length.Medium, Difficulty.Intermediate, "http://www.runehq.com/oldschoolquest/cold-war" );
		contact = 		new QuestImpl( "Contact!", 1, Length.Medium, Difficulty.Master, "http://www.runehq.com/oldschoolquest/contact" );
		cooksAssistant = 	new QuestImpl( "Cook's Assistant", 1, Length.Short, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/cook-s-assistant" );
		creatureOfFenken = 	new QuestImpl( "Creature of Fenkenstrain", 2, Length.Medium, Difficulty.Intermediate, "http://www.runehq.com/oldschoolquest/creature-of-fenkenstrain" );
		darknessOfHallowvale = 	new QuestImpl( "Darkness of Hallowvale", 2, Length.Long, Difficulty.Intermediate, "http://www.runehq.com/oldschoolquest/darkness-of-hallowvale" );
		deathPlateau = 		new QuestImpl( "Death Plateau", 1, Length.Medium, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/death-plateau" );
		deathToTheDorgeshuun = 	new QuestImpl( "Death to the Dorgeshuun", 1, Length.Medium, Difficulty.Intermediate, "http://www.runehq.com/oldschoolquest/death-to-the-dorgeshuun" );
		demonSlayer = 		new QuestImpl( "Demon Slayer", 3, Length.Medium, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/demon-slayer" );
		desertTreasure = 	new QuestImpl( "Desert Treasure", 3, Length.Long, Difficulty.Master, "http://www.runehq.com/oldschoolquest/desert-treasure" );
		deviousMinds =		new QuestImpl( "Devious Minds", 1, Length.Short, Difficulty.Experienced, "http://www.runehq.com/oldschoolquest/devious-minds" );
		digsite = 		new QuestImpl( "Digsite, The", 2, Length.Long, Difficulty.Intermediate, "http://www.runehq.com/oldschoolquest/digsite-the" );
		doricsQuest = 		new QuestImpl( "Doric's Quest", 1, Length.Short,Difficulty.Novice, "http://www.runehq.com/oldschoolquest/dorics-quest" );
		dragonSlayer = 		new QuestImpl( "Dragon Slayer", 2, Length.Long, Difficulty.Experienced, "http://www.runehq.com/oldschoolquest/dragon-slayer" );
		dreamMentor = 		new QuestImpl( "Dream Mentor", 2, Length.Short, Difficulty.Experienced, "http://www.runehq.com/oldschoolquest/dream-mentor" );
		druidicRitual =		new QuestImpl( "Druidic Ritual", 4, Length.Short, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/druidic-ritual" );
		dwarfCannon = 		new QuestImpl( "Dwarf Cannon", 1, Length.Short, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/dwarf-cannon" );
		eadgarsRuse = 		new QuestImpl( "Eadgar's Ruse", 1, Length.Medium, Difficulty.Experienced, "http://www.runehq.com/oldschoolquest/eadgars-ruse" );
		eaglesPeak =		new QuestImpl( "Eagle's Peak", 2, Length.Short, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/eagles-peak" );
		elementalWorkshopI = 	new QuestImpl( "Elemental Workshop I, The", 1, Length.Short, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/elemental-workshop-i-the" );
		elementalWorkshopII = 	new QuestImpl( "Elemental Workshop II, The", 1, Length.Short, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/elemental-workshop-ii-the" );
		enakhrasLament = 	new QuestImpl( "Enakhra's Lament", 2, Length.Medium, Difficulty.Experienced, "http://www.runehq.com/oldschoolquest/enakhras-lament" );
		enlightenedJourney = 	new QuestImpl( "Enlightened Journey", 1, Length.Medium, Difficulty.Intermediate, "http://www.runehq.com/oldschoolquest/enlightened-journey" );
		ernestTheChicken = 	new QuestImpl( "Ernest the Chicken", 4, Length.Short, Difficulty.Novice, "http://www.runehq.com/oldschoolquest/ernest-the-chicken" );
		eyesOfGlouphrie = 	new QuestImpl( "Eyes of Glouphrie, The", 2, Length.Medium, Difficulty.Intermediate, "http://www.runehq.com/oldschoolquest/eyes-of-glouphrie-the" );
		fairytaleI = 		new QuestImpl( "Fairytale I - Growing Pains", 2, Length.Long, Difficulty.Experienced, "http://www.runehq.com/oldschoolquest/fairytale-i-growing-pains" );
		fairytaleII = 		new QuestImpl( "Fairytale II - Cure a Queen", 2, Length.Medium, Difficulty.Intermediate, "http://www.runehq.com/oldschoolquest/fairytale-ii-cure-a-queen" );
		familyCrest = 		new QuestImpl( "Family Crest", 1, Length.Long, Difficulty.Experienced, "http://www.runehq.com/oldschoolquest/family-crest" );
		feud = 			new QuestImpl( "Feud, The", 1, Length.Medium, Difficulty.Intermediate, "http://www.runehq.com/oldschoolquest/feud-the" );
		fightArena = 		new QuestImpl( "Fight Arena", 2, Length.Medium, Difficulty.Experienced, "http://www.runehq.com/oldschoolquest/fight-arena" );
		fishingContest = 	new QuestImpl( "Fishing Contest", Difficulty.Novice, Length.Short, 1, "http://www.runehq.com/oldschoolquest/fishing-contest" );
		forgettableTale = 	new QuestImpl( "Forgettable Tale of a Drunken Dwarf", Difficulty.Intermediate,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/forgettable-tale-of-a-drunken-dwarf");
		fremennikIsles = 	new QuestImpl( "Fremennik Isles, The", Difficulty.Experienced,	Length.Long,	1, "http://www.runehq.com/oldschoolquest/fremennik-isles-the");
		fremennikTrials = 	new QuestImpl( "Fremennik Trials, The", Difficulty.Intermediate,	Length.Long,	3, "http://www.runehq.com/oldschoolquest/fremennik-trials-the");
		gardenOfTranquility = 	new QuestImpl( "Garden of Tranquility", Difficulty.Intermediate,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/garden-of-tranquillity");
		gertrudesCat = 		new QuestImpl( "Gertrude's Cat", Difficulty.Novice,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/gertrudes-cat");
		ghostsAhoy = 		new QuestImpl( "Ghosts Ahoy", Difficulty.Intermediate,	Length.Long,	2, "http://www.runehq.com/oldschoolquest/ghosts-ahoy");
		giantDwarf = 		new QuestImpl( "Giant Dwarf, The", Difficulty.Intermediate,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/giant-dwarf-the");
		goblinDiplomacy = 	new QuestImpl( "Goblin Diplomacy", Difficulty.Novice,	Length.Medium,	5, "http://www.runehq.com/oldschoolquest/goblin-diplomacy");
		golem = 		new QuestImpl( "Golem, The", Difficulty.Intermediate,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/golem-the");
		grandTree = 		new QuestImpl( "Grand Tree, The", Difficulty.Experienced,	Length.Long,	5, "http://www.runehq.com/oldschoolquest/grand-tree-the");
		greatBrainRobbery = 	new QuestImpl( "Great Brain Robbery, The", Difficulty.Experienced,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/great-brain-robbery-the");
		grimTales = 		new QuestImpl( "Grim Tales", Difficulty.Master,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/grim-tales");
		handInTheSand = 	new QuestImpl( "Hand in the Sand, The", Difficulty.Experienced,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/hand-in-the-sand-the");
		hauntedMine = 		new QuestImpl( "Haunted Mine", Difficulty.Experienced,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/haunted-mine");
		hazeelCult = 		new QuestImpl( "Hazeel Cult", Difficulty.Novice,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/hazeel-cult");
		heroesQuest = 		new QuestImpl( "Heroes' Quest", Difficulty.Experienced,	Length.Long,	1, "http://www.runehq.com/oldschoolquest/heroes-quest");
		holyGrail = 		new QuestImpl( "Holy Grail", Difficulty.Intermediate,	Length.Long,	2, "http://www.runehq.com/oldschoolquest/holy-grail");
		horrorFromTheDeep = 	new QuestImpl( "Horror From The Deep", Difficulty.Experienced,	Length.Short,	2, "http://www.runehq.com/oldschoolquest/horror-from-the-deep");
		icthlarinsHelper = 	new QuestImpl( "Icthlarin's Little Helper", Difficulty.Intermediate,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/icthlarins-little-helper");
		impCatcher = 		new QuestImpl( "Imp Catcher", Difficulty.Novice,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/imp-catcher");
		inAidOfTheMyreque = 	new QuestImpl( "In Aid of the Myreque", Difficulty.Intermediate,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/in-aid-of-the-myreque");
		inSearchOfTheMyreque = 	new QuestImpl( "In Search of the Myreque", Difficulty.Intermediate,	Length.Short,	2, "http://www.runehq.com/oldschoolquest/in-search-of-the-myreque");
		junglePotion = 		new QuestImpl( "Jungle Potion", Difficulty.Novice,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/jungle-potion");
		kingsRansom = 		new QuestImpl( "King's Ransom", Difficulty.Experienced,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/kings-ransom");
		knightsSword = 		new QuestImpl( "Knight's Sword, The", Difficulty.Intermediate,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/knights-sword-the");
		legendsQuest = 		new QuestImpl( "Legends' Quest", Difficulty.Master,	Length.Long,	4, "http://www.runehq.com/oldschoolquest/legends-quest");
		lostCity = 		new QuestImpl( "Lost City", Difficulty.Experienced,	Length.Medium,	3, "http://www.runehq.com/oldschoolquest/lost-city");
		lostTribe = 		new QuestImpl( "Lost Tribe, The", Difficulty.Intermediate,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/lost-tribe-the");
		lunarDiplomacy = 	new QuestImpl( "Lunar Diplomacy", Difficulty.Intermediate,	Length.Long,	2, "http://www.runehq.com/oldschoolquest/lunar-diplomacy");
		makingHistory = 	new QuestImpl( "Making History", Difficulty.Intermediate,	Length.Medium,	3, "http://www.runehq.com/oldschoolquest/making-history");
		merlinsCrystal = 	new QuestImpl( "Merlin's Crystal", Difficulty.Intermediate,	Length.Long,	6, "http://www.runehq.com/oldschoolquest/merlins-crystal");
		monksFriend = 		new QuestImpl( "Monk's Friend", Difficulty.Novice,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/monks-friend");
		monkeyMadness = 	new QuestImpl( "Monkey Madness", Difficulty.Master,	Length.Long, 3 , "http://www.runehq.com/oldschoolquest/monkey-madness");
		monkeyMadnessII = 	new QuestImpl( "Monkey Madness II", Difficulty.Grandmaster,	Length.Long, 4, "http://www.runehq.com/oldschoolquest/monkey-madness-ii" );
		mountainDaughter = 	new QuestImpl( "Mountain Daughter", Difficulty.Intermediate,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/mountain-daughter");
		mourningsEndI = 	new QuestImpl( "Mourning's Ends Part I", Difficulty.Master,	Length.Long,	2, "http://www.runehq.com/oldschoolquest/mournings-ends-part-i");
		mourningsEndII = 	new QuestImpl( "Mourning's Ends Part II", Difficulty.Master,	Length.Long,	2, "http://www.runehq.com/oldschoolquest/mournings-ends-part-ii-the-temple-of-light");
		murderMystery = 	new QuestImpl( "Murder Mystery", Difficulty.Novice,	Length.Short,	3, "http://www.runehq.com/oldschoolquest/murder-mystery");
		myArmsBigAdventure = 	new QuestImpl( "My Arm's Big Adventure", Difficulty.Intermediate,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/my-arms-big-adventure");
		natureSpirit = 		new QuestImpl( "Nature Spirit", Difficulty.Novice,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/nature-spirit");
		observatoryQuest = 	new QuestImpl( "Observatory Quest", Difficulty.Novice,	Length.Short,	2, "http://www.runehq.com/oldschoolquest/observatory-quest");
		olafsQuest = 		new QuestImpl( "Olaf's Quest", Difficulty.Intermediate,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/olafs-quest");
		oneSmallFavour = 	new QuestImpl( "One Small Favour", Difficulty.Intermediate,	Length.Long,	2, "http://www.runehq.com/oldschoolquest/one-small-favour");
		piratesTreasure = 	new QuestImpl( "Pirate's Treasure", Difficulty.Novice,	Length.Short,	2, "http://www.runehq.com/oldschoolquest/pirates-treasure");
		plagueCity = 		new QuestImpl( "Plague City", Difficulty.Novice,	Length.Long,	1, "http://www.runehq.com/oldschoolquest/plague-city");
		priestInPeril = 	new QuestImpl( "Priest in Peril", Difficulty.Novice,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/priest-in-peril");
		princeAliRescue = 	new QuestImpl( "Prince Ali Rescue", Difficulty.Novice,	Length.Medium,	3, "http://www.runehq.com/oldschoolquest/prince-ali-rescue");
		ragAndBoneMan = 	new QuestImpl( "Rag and Bone Man", Difficulty.Novice,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/rag-and-bone-man");
		ratCatchers = 		new QuestImpl( "Rat Catchers", Difficulty.Intermediate,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/rat-catchers");
		
		recruitmentDrive = 	new QuestImpl( "Recruitment Drive", Difficulty.Novice,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/recruitment-drive");
		regicide = 		new QuestImpl( "Regicide", Difficulty.Master,	Length.Long,	3, "http://www.runehq.com/oldschoolquest/regicide");
		
		rfdCook = 		new QuestImpl( "Recipe for Disaster - Cook", Difficulty.Novice,	Length.Short,	1 , "http://www.runehq.com/oldschoolquest/recipe-for-disaster#part1");
		rfdMountainDwarf = 	new QuestImpl( "Recipe for Disaster - Mountain Dwarf", Difficulty.Novice,	Length.Short,	1 , "http://www.runehq.com/oldschoolquest/recipe-for-disaster#sub1");
		rfdGoblins = 		new QuestImpl( "Recipe for Disaster - Goblins", Difficulty.Novice,	Length.Short,	1 , "http://www.runehq.com/oldschoolquest/recipe-for-disaster#sub2");
		rfdPiratePete =		new QuestImpl( "Recipe for Disaster - Pirate Pete", Difficulty.Intermediate,	Length.Medium,	1 , "http://www.runehq.com/oldschoolquest/recipe-for-disaster#sub3");
		rfdLumbridgeGuide = 	new QuestImpl( "Recipe for Disaster - Lumbridge Guide", Difficulty.Intermediate,	Length.Short,	1 , "http://www.runehq.com/oldschoolquest/recipe-for-disaster#sub4");
		rfdEvilDave = 		new QuestImpl( "Recipe for Disaster - Evil Dave", Difficulty.Intermediate,	Length.Medium,	1 , "http://www.runehq.com/oldschoolquest/recipe-for-disaster#sub5");
		rfdSkrachUglogwee = 	new QuestImpl( "Recipe for Disaster - Skrach Uglogwee", Difficulty.Intermediate,	Length.Medium,	1 , "http://www.runehq.com/oldschoolquest/recipe-for-disaster#sub6");
		rfdSirAmikVarze = 	new QuestImpl( "Recipe for Disaster - Sir Amik Varze", Difficulty.Experienced,	Length.Long, 1 , "http://www.runehq.com/oldschoolquest/recipe-for-disaster#sub7");
		rfdKingAwowogei = 	new QuestImpl( "Recipe for Disaster - King Awowogei", Difficulty.Experienced,	Length.Long,	1 , "http://www.runehq.com/oldschoolquest/recipe-for-disaster#sub8");
		rfdFinalFights = 	new QuestImpl( "Recipe for Disaster - Final Fights", Difficulty.Experienced,	Length.Medium,	1 , "http://www.runehq.com/oldschoolquest/recipe-for-disaster#part3");
		
		romeoAndJuliet = 	new QuestImpl( "Romeo and Juliet", Difficulty.Novice,	Length.Short,	5, "http://www.runehq.com/oldschoolquest/romeo-and-juliet");
		rovingElves = 		new QuestImpl( "Roving Elves", Difficulty.Master,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/roving-elves");
		royalTrouble = 		new QuestImpl( "Royal Trouble", Difficulty.Experienced,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/royal-trouble");
		rumDeal = 		new QuestImpl( "Rum Deal", Difficulty.Experienced,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/rum-deal");
		runeMysteries = 	new QuestImpl( "Rune Mysteries", Difficulty.Novice,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/rune-mysteries");
		scorpionCatcher = 	new QuestImpl( "Scorpion Catcher", Difficulty.Intermediate,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/scorpion-catcher");
		seaSlug = 		new QuestImpl( "Sea Slug", Difficulty.Intermediate,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/sea-slug");
		shadesOfMortton = 	new QuestImpl( "Shades Of Mort'ton", Difficulty.Intermediate,	Length.Short,	3, "http://www.runehq.com/oldschoolquest/shades-of-mortton");
		shadowOfTheStorm = 	new QuestImpl( "Shadow of the Storm", Difficulty.Intermediate,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/shadow-of-the-storm");
		sheepHerder = 		new QuestImpl( "Sheep Herder", Difficulty.Novice,	Length.Short,	4, "http://www.runehq.com/oldschoolquest/sheep-herder");
		sheepShearer = 		new QuestImpl( "Sheep Shearer", Difficulty.Novice,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/sheep-shearer");
		shieldOfArrav = 	new QuestImpl( "Shield of Arrav", Difficulty.Novice,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/shield-of-arrav");
		shiloVillage = 		new QuestImpl( "Shilo Village", Difficulty.Experienced,	Length.Long,	2, "http://www.runehq.com/oldschoolquest/shilo-village");
		slugMenace = 		new QuestImpl( "Slug Menace", Difficulty.Intermediate,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/slug-menace");
		soulsBane = 		new QuestImpl( "Soul's Bane, A", Difficulty.Novice,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/souls-bane-a");
		spiritsOfTheElid = 	new QuestImpl( "Spirits of the Elid", Difficulty.Intermediate,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/spirits-of-the-elid");
		swanSong = 		new QuestImpl( "Swan Song", Difficulty.Master,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/swan-song");
		taiBwoWannaiTrio = 	new QuestImpl( "Tai Bwo Wannai Trio", Difficulty.Intermediate,	Length.Long,	2, "http://www.runehq.com/oldschoolquest/tai-bwo-wannai-trio");
		tailOfTwoCats = 	new QuestImpl( "Tail of Two Cats, A", Difficulty.Intermediate,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/tail-of-two-cats-a");
		tearsOfGuthix = 	new QuestImpl( "Tears of Guthix", Difficulty.Intermediate,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/tears-of-guthix");
		templeOfIkov = 		new QuestImpl( "Temple of Ikov", Difficulty.Experienced,	Length.Long,	1, "http://www.runehq.com/oldschoolquest/temple-of-ikov");
		restlessGhost = 	new QuestImpl( "Restless Ghost, The", Difficulty.Novice,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/the-restless-ghost");
		throneOfMiscellania = 	new QuestImpl( "Throne of Miscellania", Difficulty.Experienced,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/throne-of-miscellania");
		touristTrap = 		new QuestImpl( "Tourist Trap, The", Difficulty.Intermediate,	Length.Long,	2, "http://www.runehq.com/oldschoolquest/tourist-trap-the");
		towerOfLife = 		new QuestImpl( "Tower of Life", Difficulty.Novice,	Length.Short,	2, "http://www.runehq.com/oldschoolquest/tower-of-life");
		treeGnomeVillage = 	new QuestImpl( "Tree Gnome Village", Difficulty.Intermediate,	Length.Long,	2, "http://www.runehq.com/oldschoolquest/tree-gnome-village");
		tribalTotem = 		new QuestImpl( "Tribal Totem", Difficulty.Intermediate,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/tribal-totem");
		trollRomance = 		new QuestImpl( "Troll Romance", Difficulty.Experienced,	Length.Medium,	2, "http://www.runehq.com/oldschoolquest/troll-romance");
		trollStronghold = 	new QuestImpl( "Troll Stronghold", Difficulty.Experienced,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/troll-stronghold");
		undergroundPass = 	new QuestImpl( "Underground Pass", Difficulty.Experienced,	Length.Long,	5, "http://www.runehq.com/oldschoolquest/underground-pass");
		vampireSlayer = 	new QuestImpl( "Vampire Slayer", Difficulty.Novice,	Length.Short,	3, "http://www.runehq.com/oldschoolquest/vampire-slayer");
		wanted = 		new QuestImpl( "Wanted!", Difficulty.Intermediate,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/wanted");
		watchtower = 		new QuestImpl( "Watchtower", Difficulty.Intermediate,	Length.Long,	4, "http://www.runehq.com/oldschoolquest/watchtower");
		waterfallQuest = 	new QuestImpl( "Waterfall Quest", Difficulty.Intermediate,	Length.Long,	1, "http://www.runehq.com/oldschoolquest/waterfall-quest");
		whatLiesBelow = 	new QuestImpl( "What Lies Below", Difficulty.Intermediate,	Length.Medium,	1, "http://www.runehq.com/oldschoolquest/what-lies-below");
		witchsHouse = 		new QuestImpl( "Witch's House", Difficulty.Intermediate,	Length.Medium,	4, "http://www.runehq.com/oldschoolquest/witchs-house");
		witchsPotion = 		new QuestImpl( "Witch's Potion", Difficulty.Novice,	Length.Short,	1, "http://www.runehq.com/oldschoolquest/witchs-potion");
		zogreFleshEaters = 	new QuestImpl( "Zogre Flesh Eaters", Difficulty.Intermediate,	Length.Long,	1, "http://www.runehq.com/oldschoolquest/zogre-flesh-eaters");
		
		mageOfZamorak = 	new MiniQuest( "Mage of Zamorak", Difficulty.Novice, Length.Short, 0 , "http://www.runehq.com/miniquest/mage-of-zamorak");
		alfredBarcrawl = 	new MiniQuest( "Alfred Grimhand's Barcrawl", Difficulty.Novice, Length.Medium, 0 , "http://www.runehq.com/miniquest/the-alfred-grimhand-bar-crawl");
                skippyAndTheMogres = 	new MiniQuest( "Skippy and the Mogres", Difficulty.Novice, Length.Medium, 0 , "http://www.runehq.com/oldschoolminiquest/skippy-and-the-mogres");
                ragAndBoneManMini = 	new QuestImpl( "Rag and Bone Man Wish List", Difficulty.Novice, Length.Long, 1 , "http://2007.runescape.wikia.com/wiki/Rag_%26_Bone_Wish_List");
		
		/** Initialize quest requirements for each quest AFTER initializing each quest */
		animalMagnetism.setQuestRequirements( restlessGhost, ernestTheChicken, priestInPeril );
		anotherSliceOfHam.setQuestRequirements( deathToTheDorgeshuun, giantDwarf, digsite );
		betweenARock.setQuestRequirements( fishingContest, dwarfCannon );
		biohazard.setQuestRequirements( plagueCity );
		cabinFever.setQuestRequirements( rumDeal, piratesTreasure );
		contact.setQuestRequirements( princeAliRescue, gertrudesCat, icthlarinsHelper );
		creatureOfFenken.setQuestRequirements( restlessGhost, priestInPeril );
		darknessOfHallowvale.setQuestRequirements( inAidOfTheMyreque );
		deathToTheDorgeshuun.setQuestRequirements( lostTribe );
		desertTreasure.setQuestRequirements( digsite, touristTrap, templeOfIkov, priestInPeril, waterfallQuest, trollStronghold );
		deviousMinds.setQuestRequirements( doricsQuest, trollStronghold, wanted, mageOfZamorak );
		digsite.setQuestRequirements( druidicRitual );
		dreamMentor.setQuestRequirements( lunarDiplomacy, eadgarsRuse );
		eadgarsRuse.setQuestRequirements( trollStronghold, druidicRitual );
		elementalWorkshopII.setQuestRequirements( elementalWorkshopI );
		eyesOfGlouphrie.setQuestRequirements( grandTree );
		fairytaleI.setQuestRequirements( lostCity, natureSpirit );
		fairytaleII.setQuestRequirements( fairytaleI );
		forgettableTale.setQuestRequirements( giantDwarf, fishingContest );
		fremennikIsles.setQuestRequirements( fremennikTrials );
		gardenOfTranquility.setQuestRequirements( creatureOfFenken );
		ghostsAhoy.setQuestRequirements( restlessGhost, priestInPeril );
		greatBrainRobbery.setQuestRequirements( creatureOfFenken, rfdPiratePete, rumDeal, cabinFever );
		grimTales.setQuestRequirements( witchsHouse );
		hauntedMine.setQuestRequirements( priestInPeril );
		heroesQuest.setQuestRequirements( shieldOfArrav, merlinsCrystal, lostCity, dragonSlayer );
		holyGrail.setQuestRequirements( merlinsCrystal );
		horrorFromTheDeep.setQuestRequirements( alfredBarcrawl );
		icthlarinsHelper.setQuestRequirements( gertrudesCat );
		inAidOfTheMyreque.setQuestRequirements( inSearchOfTheMyreque );
		inSearchOfTheMyreque.setQuestRequirements( natureSpirit );
		junglePotion.setQuestRequirements( druidicRitual );
		kingsRansom.setQuestRequirements( blackKnightsfortress, merlinsCrystal, holyGrail, murderMystery, oneSmallFavour );
		legendsQuest.setQuestRequirements( familyCrest, heroesQuest, undergroundPass, shiloVillage, waterfallQuest );
		lostTribe.setQuestRequirements( runeMysteries, goblinDiplomacy );
		lunarDiplomacy.setQuestRequirements( fremennikTrials, lostCity, runeMysteries, shiloVillage );
		makingHistory.setQuestRequirements( priestInPeril, restlessGhost );
		monkeyMadness.setQuestRequirements( grandTree, treeGnomeVillage );
		monkeyMadnessII.setQuestRequirements( rfdKingAwowogei, enlightenedJourney, eyesOfGlouphrie, trollStronghold, watchtower );
		mourningsEndI.setQuestRequirements( rovingElves, sheepHerder, bigChompyBirdHunting );
		mourningsEndII.setQuestRequirements( mourningsEndI );
		myArmsBigAdventure.setQuestRequirements( eadgarsRuse, feud, junglePotion );
		natureSpirit.setQuestRequirements( restlessGhost, priestInPeril );
		olafsQuest.setQuestRequirements( fremennikTrials );
		oneSmallFavour.setQuestRequirements( runeMysteries, druidicRitual, shiloVillage );
		ratCatchers.setQuestRequirements( gertrudesCat, icthlarinsHelper );
                ragAndBoneManMini.setQuestRequirements(ragAndBoneMan, fremennikTrials, horrorFromTheDeep, waterfallQuest, zogreFleshEaters, creatureOfFenken);
		rfdCook.setQuestRequirements( cooksAssistant );
		rfdMountainDwarf.setQuestRequirements( rfdCook, fishingContest );
		rfdGoblins.setQuestRequirements( rfdCook, goblinDiplomacy );
		rfdLumbridgeGuide.setQuestRequirements( rfdCook, bigChompyBirdHunting, biohazard, demonSlayer, murderMystery, natureSpirit, priestInPeril, restlessGhost, witchsHouse );
		rfdEvilDave.setQuestRequirements( rfdCook, gertrudesCat, shadowOfTheStorm );
                rfdPiratePete.setQuestRequirements(rfdCook);
		rfdSkrachUglogwee.setQuestRequirements( rfdCook, bigChompyBirdHunting );
		rfdSirAmikVarze.setQuestRequirements( rfdCook, lostCity, legendsQuest );
		rfdKingAwowogei.setQuestRequirements( rfdCook, monkeyMadness );
		rfdFinalFights.setQuestRequirements( rfdCook, desertTreasure, horrorFromTheDeep, rfdMountainDwarf, rfdGoblins, rfdLumbridgeGuide, rfdEvilDave, rfdSkrachUglogwee, rfdKingAwowogei, rfdSirAmikVarze );
		recruitmentDrive.setQuestRequirements( blackKnightsfortress, druidicRitual );
		regicide.setQuestRequirements( undergroundPass );
		rovingElves.setQuestRequirements( waterfallQuest, regicide );
		royalTrouble.setQuestRequirements( throneOfMiscellania );
		rumDeal.setQuestRequirements( zogreFleshEaters );
		scorpionCatcher.setQuestRequirements( alfredBarcrawl );
		shadesOfMortton.setQuestRequirements( priestInPeril );
		shadowOfTheStorm.setQuestRequirements( demonSlayer, golem );
		shiloVillage.setQuestRequirements( junglePotion );
		slugMenace.setQuestRequirements( seaSlug, wanted );
		swanSong.setQuestRequirements( oneSmallFavour, gardenOfTranquility );
		taiBwoWannaiTrio.setQuestRequirements( junglePotion );
		tailOfTwoCats.setQuestRequirements( icthlarinsHelper, gertrudesCat );
		throneOfMiscellania.setQuestRequirements( fremennikTrials, heroesQuest );
		trollRomance.setQuestRequirements( trollStronghold );
		trollStronghold.setQuestRequirements( deathPlateau );
		undergroundPass.setQuestRequirements( biohazard );
		wanted.setQuestRequirements( recruitmentDrive, priestInPeril, lostTribe, runeMysteries, mageOfZamorak );
		whatLiesBelow.setQuestRequirements( runeMysteries );
		zogreFleshEaters.setQuestRequirements( junglePotion, bigChompyBirdHunting );
		
		
		/** Initialize skill requirements for each quest */
		animalMagnetism.setSkillRequirements( new SkillRequirement( Type.Slayer, 18 ), new SkillRequirement( Type.Crafting, 19 ), new SkillRequirement( Type.Woodcutting, 35 ) );
		anotherSliceOfHam.setSkillRequirements( new SkillRequirement( Type.Attack, 15 ), new SkillRequirement( Type.Prayer, 25 ) );
		betweenARock.setSkillRequirements( csr( Type.Defence, 30 ), csr(Type.Smithing, 50), csr(Type.Mining,  40) );
		bigChompyBirdHunting.setSkillRequirements( new SkillRequirement(Type.Fletching, 5), new SkillRequirement( Type.Cooking, 30), new SkillRequirement(Type.Ranged, 30));
		blackKnightsfortress.setSkillRequirements( new SkillRequirement( Type.Quest, 12 ) );
		cabinFever.setSkillRequirements( csr(Type.Agility, 42), csr(Type.Crafting, 45), csr(Type.Smithing, 50), csr(Type.Ranged, 40) );
		coldWar.setSkillRequirements( csr(Type.Hunter, 10), csr(Type.Thieving, 15), csr( Type.Agility, 30), csr(Type.Crafting, 30), csr(Type.Construction, 34));
		creatureOfFenken.setSkillRequirements( csr(Type.Thieving, 25), csr( Type.Crafting, 20 ));
		darknessOfHallowvale.setSkillRequirements( csr(Type.Construction, 5), csr(Type.Mining, 20), csr( Type.Thieving, 22), csr( Type.Agility, 26), csr(Type.Crafting, 32), csr(Type.Magic, 33), csr(Type.Strength, 40));
		deathToTheDorgeshuun.setSkillRequirements( csr(Type.Agility, 23), csr(Type.Thieving, 23) );
		desertTreasure.setSkillRequirements( csr(Type.Slayer, 10), csr(Type.Firemaking, 50), csr(Type.Magic, 50), csr(Type.Thieving, 53));
		deviousMinds.setSkillRequirements( csr(Type.Smithing, 65), csr(Type.Fletching, 50), csr(Type.Runecraft, 50));
		digsite.setSkillRequirements(csr(Type.Thieving, 25), csr(Type.Agility, 10), csr(Type.Herblore, 10));
		dragonSlayer.setSkillRequirements( csr(Type.Quest, 32) );
		dreamMentor.setSkillRequirements( csr(Type.Combat, 85) );
		eadgarsRuse.setSkillRequirements( csr(Type.Herblore, 31) );
		eaglesPeak.setSkillRequirements( csr( Type.Hunter, 27 ) );
		elementalWorkshopI.setSkillRequirements( csr(Type.Mining, 20), csr(Type.Smithing, 20), csr(Type.Crafting, 20));
		elementalWorkshopII.setSkillRequirements( csr(Type.Magic, 20), csr(Type.Smithing, 30) );
		enakhrasLament.setSkillRequirements( csr(Type.Crafting, 50), csr(Type.Firemaking, 45), csr(Type.Prayer, 43), csr(Type.Magic, 39));
		enlightenedJourney.setSkillRequirements( csr(Type.Firemaking, 20), csr(Type.Farming, 30), csr(Type.Crafting, 36), csr(Type.Quest, 20));
		eyesOfGlouphrie.setSkillRequirements( csr(Type.Construction, 5), csr(Type.Magic, 46));
		fairytaleII.setSkillRequirements( csr(Type.Herblore, 57), csr(Type.Farming, 49), csr(Type.Thieving, 40));
		familyCrest.setSkillRequirements( csr(Type.Mining, 40), csr(Type.Smithing, 40), csr(Type.Crafting, 40), csr(Type.Magic, 59));
		feud.setSkillRequirements( csr(Type.Thieving, 30) );
		fishingContest.setSkillRequirements( csr(Type.Fishing, 10));
		forgettableTale.setSkillRequirements(csr(Type.Farming, 17), csr(Type.Cooking, 22));
		fremennikIsles.setSkillRequirements( csr(Type.Construction, 20), csr(Type.Agility, 40), csr(Type.Crafting, 46), csr(Type.Woodcutting, 56));
		fremennikTrials.setSkillRequirements( csr(Type.Woodcutting, 40), csr(Type.Crafting,40), csr(Type.Fletching, 25) );
		gardenOfTranquility.setSkillRequirements( csr(Type.Farming, 25));
		ghostsAhoy.setSkillRequirements(csr(Type.Agility, 25), csr(Type.Cooking, 20));
		giantDwarf.setSkillRequirements(csr(Type.Magic, 33), csr(Type.Firemaking, 16), csr(Type.Thieving, 14), csr(Type.Crafting, 12));
		golem.setSkillRequirements( csr(Type.Crafting, 20), csr(Type.Thieving, 25));
		grandTree.setSkillRequirements( csr(Type.Agility, 25));
		greatBrainRobbery.setSkillRequirements(csr(Type.Crafting,16), csr(Type.Construction, 30), csr(Type.Prayer, 50));
		grimTales.setSkillRequirements( csr(Type.Farming, 45), csr(Type.Herblore, 52), csr(Type.Thieving, 58), csr(Type.Agility, 59), csr(Type.Woodcutting, 71));
		handInTheSand.setSkillRequirements( csr(Type.Thieving, 17), csr(Type.Crafting, 49));
		hauntedMine.setSkillRequirements( csr(Type.Agility, 15), csr(Type.Crafting, 35) );
		heroesQuest.setSkillRequirements( csr(Type.Quest, 55), csr(Type.Herblore, 25), csr(Type.Mining, 50), csr(Type.Fishing, 53), csr(Type.Cooking, 53));
		holyGrail.setSkillRequirements(csr(Type.Attack, 30));
		horrorFromTheDeep.setSkillRequirements(csr(Type.Agility, 35));
		inAidOfTheMyreque.setSkillRequirements(csr(Type.Mining, 15), csr(Type.Crafting, 25), csr(Type.Magic, 7));
		inSearchOfTheMyreque.setSkillRequirements(csr(Type.Agility, 25));
		junglePotion.setSkillRequirements(Type.Herblore, 3);
		kingsRansom.setSkillRequirements(csr(Type.Magic, 45), csr(Type.Defence, 65));
		knightsSword.setSkillRequirements( Type.Mining, 10 );
		legendsQuest.setSkillRequirements( csr(Type.Magic, 56), csr(Type.Quest, 107), csr(Type.Mining, 52),
				csr(Type.Agility, 50), csr(Type.Crafting, 50), csr(Type.Smithing, 50), csr(Type.Strength, 50),
				csr(Type.Thieving, 50), csr(Type.Woodcutting, 50), csr(Type.Herblore, 45), csr(Type.Prayer, 42));
		lostCity.setSkillRequirements( csr(Type.Crafting, 31), csr(Type.Woodcutting, 36));
		lostTribe.setSkillRequirements( csr(Type.Mining, 17), csr(Type.Agility, 13), csr(Type.Thieving, 13));
		lunarDiplomacy.setSkillRequirements( csr(Type.Crafting, 61), csr(Type.Defence, 40), csr(Type.Firemaking, 49),
				csr(Type.Herblore, 5), csr(Type.Magic, 65), csr(Type.Mining, 60), csr(Type.Woodcutting, 55));
		merlinsCrystal.setSkillRequirements(Type.Attack, 20);
		monkeyMadnessII.setSkillRequirements(csr(Type.Crafting, 70), csr(Type.Slayer, 69), csr(Type.Hunter, 60), csr(Type.Agility, 55), csr(Type.Thieving, 55));
		mountainDaughter.setSkillRequirements(Type.Agility, 20);
		mourningsEndI.setSkillRequirements(csr(Type.Ranged, 60), csr(Type.Thieving, 50));
		myArmsBigAdventure.setSkillRequirements(csr(Type.Woodcutting, 10), csr(Type.Farming, 29));
		natureSpirit.setSkillRequirements(Type.Crafting, 18);
		observatoryQuest.setSkillRequirements(Type.Crafting, 10);
		olafsQuest.setSkillRequirements(csr(Type.Firemaking, 40), csr(Type.Woodcutting, 50));
		oneSmallFavour.setSkillRequirements(csr(Type.Crafting, 25), csr(Type.Herblore, 18), csr(Type.Agility, 36), csr(Type.Smithing, 30));
		ragAndBoneManMini.setSkillRequirements(csr(Type.Slayer, 40), csr(Type.Defence, 20));
		rfdCook.setSkillRequirements(Type.Cooking, 10);
		rfdPiratePete.setSkillRequirements(Type.Cooking, 31);
		rfdLumbridgeGuide.setSkillRequirements(Type.Cooking, 40);
		rfdEvilDave.setSkillRequirements(Type.Cooking, 25);
		rfdSkrachUglogwee.setSkillRequirements(csr(Type.Cooking, 41), csr(Type.Firemaking, 20));
		rfdKingAwowogei.setSkillRequirements(csr(Type.Cooking, 70), csr(Type.Agility, 48));
		rfdFinalFights.setSkillRequirements(Type.Quest, 175);
		
		recruitmentDrive.setSkillRequirements(Type.Quest, 12);
		regicide.setSkillRequirements(csr(Type.Agility, 56), csr(Type.Crafting, 10));
		royalTrouble.setSkillRequirements(csr(Type.Agility, 40), csr(Type.Slayer, 40));
		rumDeal.setSkillRequirements(csr(Type.Farming, 40), csr(Type.Fishing, 50), csr(Type.Prayer, 47), csr(Type.Crafting, 42), csr(Type.Slayer, 42));
		scorpionCatcher.setSkillRequirements(Type.Prayer, 31);
		seaSlug.setSkillRequirements(Type.Firemaking, 30);
		shadesOfMortton.setSkillRequirements(csr(Type.Herblore, 15), csr(Type.Crafting, 20));
		shadowOfTheStorm.setSkillRequirements(Type.Crafting, 30);
		shiloVillage.setSkillRequirements(csr(Type.Agility, 32), csr(Type.Crafting, 20));
                skippyAndTheMogres.setSkillRequirements(csr(Type.Cooking, 20), csr(Type.Slayer, 32));
		slugMenace.setSkillRequirements(csr(Type.Crafting, 30), csr(Type.Runecraft, 30), csr(Type.Slayer, 30), csr(Type.Thieving, 30));
		spiritsOfTheElid.setSkillRequirements(csr(Type.Magic, 33), csr(Type.Ranged, 37), csr(Type.Mining, 37), csr(Type.Thieving, 37));
		swanSong.setSkillRequirements(csr(Type.Magic, 66), csr(Type.Cooking, 62), csr(Type.Fishing, 62), csr(Type.Smithing, 45), csr(Type.Firemaking, 42), csr(Type.Crafting, 40));
		taiBwoWannaiTrio.setSkillRequirements(csr(Type.Cooking, 30), csr(Type.Agility, 15), csr(Type.Fishing, 5) );
		tearsOfGuthix.setSkillRequirements(csr(Type.Firemaking, 49), csr(Type.Crafting, 20), csr(Type.Mining, 20), csr(Type.Quest, 44));
		templeOfIkov.setSkillRequirements(csr(Type.Ranged,40), csr(Type.Thieving, 42));
		throneOfMiscellania.setSkillRequirements(csr(Type.Mining, 30), csr(Type.Herblore, 35),csr(Type.Woodcutting, 45), csr(Type.Fishing, 35));
		touristTrap.setSkillRequirements(csr(Type.Smithing, 20), csr(Type.Fletching, 10));
		towerOfLife.setSkillRequirements(Type.Construction, 10);
		tribalTotem.setSkillRequirements(Type.Thieving, 21);
		trollRomance.setSkillRequirements(Type.Agility, 28);
		trollStronghold.setSkillRequirements(Type.Agility, 15);
		undergroundPass.setSkillRequirements(Type.Ranged, 25);
		wanted.setSkillRequirements(Type.Quest, 32);
		watchtower.setSkillRequirements(csr(Type.Herblore, 14), csr(Type.Magic, 14), csr(Type.Thieving, 15), csr(Type.Agility, 25), csr(Type.Mining, 40) );
		whatLiesBelow.setSkillRequirements(Type.Runecraft, 35);
		zogreFleshEaters.setSkillRequirements(csr(Type.Herblore,8), csr(Type.Ranged, 30), csr(Type.Smithing, 4), csr(Type.Fletching, 30));
		
		/** Add all quests to allQuestSet */
		allQuestSet = new HashSet<Quest>();
		
		allQuestSet.add( animalMagnetism );
		allQuestSet.add( anotherSliceOfHam );
		allQuestSet.add( betweenARock );
		allQuestSet.add( bigChompyBirdHunting );
		allQuestSet.add( biohazard );
		allQuestSet.add( blackKnightsfortress );
		allQuestSet.add( cabinFever );
		allQuestSet.add( clockTower );
		allQuestSet.add( coldWar );
		allQuestSet.add( contact );
		allQuestSet.add( cooksAssistant );
		allQuestSet.add( creatureOfFenken );
		allQuestSet.add( darknessOfHallowvale );
		allQuestSet.add( deathPlateau );
		allQuestSet.add( deathToTheDorgeshuun );
		allQuestSet.add( demonSlayer );
		allQuestSet.add( desertTreasure );
		allQuestSet.add( deviousMinds );
		allQuestSet.add( digsite );
		allQuestSet.add( doricsQuest );
		allQuestSet.add( dragonSlayer );
		allQuestSet.add( dreamMentor );
		allQuestSet.add( druidicRitual );
		allQuestSet.add( dwarfCannon );
		allQuestSet.add( eadgarsRuse );
		allQuestSet.add( eaglesPeak );
		allQuestSet.add( elementalWorkshopI );
		allQuestSet.add( elementalWorkshopII );
		allQuestSet.add( enakhrasLament );
		allQuestSet.add( enlightenedJourney );
		allQuestSet.add( ernestTheChicken );
		allQuestSet.add( eyesOfGlouphrie );
		allQuestSet.add( fairytaleI );
		allQuestSet.add( fairytaleII );
		allQuestSet.add( familyCrest );
		allQuestSet.add( feud );
		allQuestSet.add( fightArena ) ;
		allQuestSet.add( fishingContest );
		allQuestSet.add( forgettableTale );
		allQuestSet.add( fremennikIsles );
		allQuestSet.add( fremennikTrials );
		allQuestSet.add( gardenOfTranquility );
		allQuestSet.add( gertrudesCat );
		allQuestSet.add( ghostsAhoy );
		allQuestSet.add( giantDwarf );
		allQuestSet.add( goblinDiplomacy );
		allQuestSet.add( golem );
		allQuestSet.add( grandTree );
		allQuestSet.add( greatBrainRobbery );
		allQuestSet.add( grimTales );
		allQuestSet.add( handInTheSand );
		allQuestSet.add( hauntedMine );
		allQuestSet.add( hazeelCult );
		allQuestSet.add( heroesQuest );
		allQuestSet.add( holyGrail );
		allQuestSet.add( horrorFromTheDeep );
		allQuestSet.add( icthlarinsHelper );
		allQuestSet.add( impCatcher );
		allQuestSet.add( inAidOfTheMyreque );
		allQuestSet.add( inSearchOfTheMyreque );
		allQuestSet.add( junglePotion );
		allQuestSet.add( kingsRansom );
		allQuestSet.add( knightsSword );
		allQuestSet.add( legendsQuest );
		allQuestSet.add( lostCity );
		allQuestSet.add( lostTribe );
		allQuestSet.add( lunarDiplomacy );
		allQuestSet.add( makingHistory );
		allQuestSet.add( merlinsCrystal );
		allQuestSet.add( monksFriend );
		allQuestSet.add( monkeyMadness );
		allQuestSet.add( monkeyMadnessII );
		allQuestSet.add( mountainDaughter );
		allQuestSet.add( mourningsEndI );
		allQuestSet.add( mourningsEndII );
		allQuestSet.add( murderMystery );
		allQuestSet.add( myArmsBigAdventure );
		allQuestSet.add( natureSpirit );
		allQuestSet.add( observatoryQuest );
		allQuestSet.add( olafsQuest );
		allQuestSet.add( oneSmallFavour );
		allQuestSet.add( piratesTreasure );
		allQuestSet.add( plagueCity );
		allQuestSet.add( priestInPeril );
		allQuestSet.add( princeAliRescue );
		allQuestSet.add( ragAndBoneMan );
                allQuestSet.add( ragAndBoneManMini );
		allQuestSet.add( ratCatchers );
		allQuestSet.add( rfdCook );
		allQuestSet.add( rfdMountainDwarf );
		allQuestSet.add( rfdGoblins );
		allQuestSet.add( rfdPiratePete );
		allQuestSet.add( rfdLumbridgeGuide );
		allQuestSet.add( rfdEvilDave );
		allQuestSet.add( rfdSkrachUglogwee );
		allQuestSet.add( rfdKingAwowogei );
		allQuestSet.add( rfdSirAmikVarze );
		allQuestSet.add( rfdFinalFights );
		allQuestSet.add( recruitmentDrive );
		allQuestSet.add( regicide );
		allQuestSet.add( romeoAndJuliet );
		allQuestSet.add( rovingElves );
		allQuestSet.add( royalTrouble );
		allQuestSet.add( rumDeal );
		allQuestSet.add( runeMysteries );
		allQuestSet.add( scorpionCatcher );
		allQuestSet.add( seaSlug );
		allQuestSet.add( shadesOfMortton );
		allQuestSet.add( shadowOfTheStorm );
		allQuestSet.add( sheepHerder );
		allQuestSet.add( sheepShearer );
		allQuestSet.add( shieldOfArrav );
		allQuestSet.add( shiloVillage );
		allQuestSet.add( slugMenace );
		allQuestSet.add( soulsBane );
		allQuestSet.add( spiritsOfTheElid );
		allQuestSet.add( swanSong );
		allQuestSet.add( taiBwoWannaiTrio );
		allQuestSet.add( tailOfTwoCats );
		allQuestSet.add( tearsOfGuthix );
		allQuestSet.add( templeOfIkov );
		allQuestSet.add( restlessGhost );
		allQuestSet.add( throneOfMiscellania );
		allQuestSet.add( touristTrap );
		allQuestSet.add( towerOfLife );
		allQuestSet.add( treeGnomeVillage );
		allQuestSet.add( tribalTotem );
		allQuestSet.add( trollRomance );
		allQuestSet.add( trollStronghold );
		allQuestSet.add( undergroundPass );
		allQuestSet.add( vampireSlayer );
		allQuestSet.add( wanted );
		allQuestSet.add( watchtower );
		allQuestSet.add( waterfallQuest );
		allQuestSet.add( whatLiesBelow );
		allQuestSet.add( witchsHouse );
		allQuestSet.add( witchsPotion );
		allQuestSet.add( zogreFleshEaters );
		allQuestSet.add( mageOfZamorak );
		allQuestSet.add( alfredBarcrawl );
		
	}
	
	/**
	 * create skill requirement (csr)
	 * @param type
	 * @param level
	 * @return
	 */
private static SkillRequirement csr( Type type, int level )
{
	return new SkillRequirement( type, level );
}
	
	
}
